environment:
  matrix:
    - nodejs_version: "4.4"
    - nodejs_version: "5"
    - nodejs_version: "6.2"

init:
  - git config --global core.autocrlf true
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run test:once

build: off
